"""Add Application model

Revision ID: 75c9c20a8ece
Revises: 475d2c81cc23
Create Date: 2025-12-22 14:34:41.748591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c9c20a8ece'
down_revision: Union[str, None] = '475d2c81cc23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWING', 'INTERVIEW', 'REJECTED', 'ACCEPTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_applied_at'), ['applied_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_applications_job_status', ['job_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index('ix_applications_unique_user_job', ['user_id', 'job_id'], unique=True)
        batch_op.create_index('ix_applications_user_applied_at', ['user_id', 'applied_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_companies_managed_by_id_users', 'users', ['managed_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_foreign_key('fk_jobs_created_by_id_users', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_created_by_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_created_by_id'))
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_managed_by_id_users', type_='foreignkey')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index('ix_applications_user_applied_at')
        batch_op.drop_index('ix_applications_unique_user_job')
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index('ix_applications_job_status')
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))
        batch_op.drop_index(batch_op.f('ix_applications_id'))
        batch_op.drop_index(batch_op.f('ix_applications_applied_at'))

    op.drop_table('applications')
    # ### end Alembic commands ###
